server:
  port: 80

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  web:
    resources:
      chain:
        cache: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
